version: '2'  
services:  
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/etc/nginx/vhost.d'
            - '/usr/share/nginx/html'
            - '/etc/nginx/certs:/etc/nginx/certs:ro' 
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        restart: on-failure

    letsencrypt-nginx-proxy:
        container_name: letsencrypt-nginx-proxy
        image: 'jrcs/letsencrypt-nginx-proxy-companion'
        volumes:
            - '/etc/nginx/certs:/etc/nginx/certs'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        volumes_from:
            - nginx-proxy
        restart: on-failure

    librepatron:
        container_name: librepatron
        image: jvandrew/librepatron:0.6.41
        expose:
            - "8006"
        volumes:
            - data-volume:/var/lib/db
            - config-volume:/var/lib/config
        environment:
            - DATABASE_URL=sqlite:////var/lib/db/app.db
        env_file:
            - librepatron.env
        restart: on-failure

    isso:
        container_name: isso
        image: jvandrew/isso:atron.13
        expose:
            - "8080"
        volumes:
            - data-volume:/var/lib/db
            - config-volume:/var/lib/config
        env_file:
            - isso.env
        restart: on-failure

volumes:
    data-volume:
        driver: local
    config-volume:
        driver: local

networks:  
  default:
    external:
      name: nginx-net
